### ISSUE TITLE
Program do przechowywania czapek

### ISSUE THREAD

**Issue by szymonleyk** [juliandzialak/java#3]
Czapka ma rozmiar, kolor
Można dodawać czapki
Można szukać czapki po kolorze.... wyświetl tylko te o podanym kolorze.

**Comment by juliandzialak** [comment]
Hej

Bardzo przepraszam była zmiana czasu na letni i teraz zauważyłem że jest
godzina 9.

Jeszcze raz bardzo przerpaszam.

czw., 25 mar 2021 o 08:02 Szymon Leyk ***@***.***> napisał(a):
